# MongoDB connection
MONGO_URI = "mongodb+srv://vineelnani16_db_user:pvMq8DXo42Vzg1l7@cluster0.r9r5wqq.mongodb.net/"
DB_NAME = "beepbeep_DB"

# Dataset root for ingestion (local machine only)
DATASET_ROOT = "yt_to_frames/frames_out"

# Default labeling config
DEFAULT_ANNOTATOR = "user1"
DEFAULT_CLIP_LEN = 4
DEFAULT_DHASH_THRESHOLD = 6
DEFAULT_JPG_QUALITY = 90
